<a href="https://colab.research.google.com/github/gkrishna-sree/aiml-lab-batch5/blob/main/assignment1_part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Implement basic data structures with numpy and pandas.

List

In [ ]:
list1 = [1, 4, 6, 9]
print(list1)

[1, 4, 6, 9]


In [ ]:
list1.append(10)
print(list1)

[1, 4, 6, 9, 10]


In [ ]:
list1.insert(2, 3)
print(list1)

[1, 4, 3, 6, 9, 10]


In [ ]:
list3 = [0, 5, 7]
list1.extend(list3)
print(list1)

[1, 4, 3, 6, 9, 10, 0, 5, 7]


In [ ]:
list1.pop()
print(list1)

[1, 4, 3, 6, 9, 10, 0, 5]


In [ ]:
list1.pop(1)
print(list1)

[1, 3, 6, 9, 10, 0, 5]


In [ ]:
list1.remove(6)
print(list1)

[1, 3, 9, 10, 0, 5]


Array

In [ ]:
import numpy as np
list2 = [33, 76, 12, 56]
arr1 = np.array(list2)
print(arr1)

[33 76 12 56]


In [ ]:
print('dimensions: ',arr1.ndim)

dimensions:  1


In [ ]:
array2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print('dimensions: ',array2d.ndim)

dimensions:  2


In [ ]:
array3d = np.array([[[1, 2],[4, 5]],[[7, 8],[10, 11]]])
print(array3d)

[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


In [ ]:
print('dimensions: ',array3d.ndim)

dimensions:  3


type()

In [ ]:
print(type(list1))

<class 'list'>


In [ ]:
a = True
print(type(a))

<class 'bool'>


In [ ]:
a = 9.0
print(type(a))

<class 'float'>


In [ ]:
a = 'a'
print(type(a))

<class 'str'>


In [ ]:
a = 99
print(type(a))

<class 'int'>


In [ ]:
a =123456789098765432123456789012345678901234567890
print(type(a))

<class 'int'>


Perform mathematical operations:

In [ ]:
print(arr1)

[33 76 12 56]


In [ ]:
result = arr1 * 2

In [ ]:
print(result)

[ 66 152  24 112]


In [ ]:
result1 = arr1/2

In [ ]:
print(result1)

[16.5 38.   6.  28. ]


In [ ]:
result_poweroff = np.power(arr1, 2)
print(result_poweroff)


[1089 5776  144 3136]


In [ ]:
text_output = f"Addition of Two: {arr1 + arr1}"
print(text_output)

Addition of Two: [ 66 152  24 112]


In [ ]:
print("Sin:", np.sin(arr1))
print("Log:", np.log(arr1))
print("Exponential:", np.exp(arr1))
print("Log2:", np.log2(arr1))

Sin: [ 0.99991186  0.56610764 -0.53657292 -0.521551  ]
Log: [3.49650756 4.33073334 2.48490665 4.02535169]
Exponential: [2.14643580e+14 1.01480039e+33 1.62754791e+05 2.09165950e+24]
Log2: [5.04439412 6.24792751 3.5849625  5.80735492]
